#!/usr/bin/bash
# Script transfers file from client to server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit()
fi

FILE_PATH = $1
SERVER_IP = $2
USERNAME = $3
SSH_KEY = $4

scp -o StrickHostKeyChecking=no -i $SSH_KEY $FILE_PATH $USERNAME@$SERVER_IP:~/
