#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine to install nginx

sudo apt update -y # Update...

sudo apt upgrade -y # Upgrade...

sudo apt install nginx -y # Install Nginx and answer yes to all prompts

Hello="Hello World"
echo "$Hello" > /var/www/html/index.html

# Test the Nginx configuration and reload the service
sudo nginx -t && sudo /etc/init.d/nginx reload
