#!/usr/bin/env bash
# Script that configures server so that /redirect_me == '301 Moved Permanently'

sudo apt update -y

sudo apt install nginx -y

# Index page
echo "Hello World!" >/var/www/html/index.nginx-debian.html

# Configure Nginx server to redirect '/redirect_me'
sed -i 's/server_name _;/&\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default

# sed -i 's/location \/ /location \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default

# Restart server
sudo service nginx restart
