#!/usr/bin/env bash
# Script that configures server so that /redirect_me == '301 Moved Permanently'
#!/bin/bash

if dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -q "^install ok installed$"; then
	echo "Nginx is already installed"
else
	echo "Installing Nginx"
	sudo apt-get update
	sudo apt-get install -y nginx
fi

# Index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx server to redirect '/redirect_me'
sudo sed -i 's/server_name _;/&\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default

# Restart server
sudo service nginx restart
