#!/usr/bin/env bash
# Script that configures server to have a custom error 404 page

sudo apt update -y &_ sudo apt upgrade -y

sudo apt install nginx -y

# Index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure Nginx server to redirect '/redirect_me'
sed -i 's/server_name _;/&\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default

# Create error 404 page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Configure custom error page for Nginx server
sed -i 's/server_name _;/&\n\n\terror_page 404 \/error_404.html;\n\tlocation \/error_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Give proper permissions
sudo chown www-data:www-data /var/www/html/error_404.html
sudo chmod 644 /var/www/html/error_404.html

# Restart server
sudo service nginx restart
