#!/usr/bin/env bash
# Script that configures server to have a custom error 404 page

if dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -q "^install ok installed$"; then
	echo "Nginx is already installed"
else
	echo "Installing Nginx"
	sudo apt-get update
	sudo apt-get install -y nginx
fi

# Index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Config text for redirection
block = "
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
"

# Define path for congire file
config_file = "/etc/nginx/sites-available/default"

# Configure Nginx server to redirect '/redirect_me'
if ! grep -qF "$block" "$config_file"; then
	sudo sed -i '/location \/ {/a'"$block"'' "$config_file"
fi
# sudo sed -i 's/server_name _;/&\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default

# Config text for error 404
error_block = "
	error_404 404 /error_404.html;
	location /error_404.html {
		root /var/www/html;
		internal;
	}
"
# Create error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null

# Configure custom error page for Nginx server
if ! grep -qF "$error_block" "$config_file"; then
	sudo sed -i '/location \/ {/a'"$error_block"'' "$config_file"
fi
# sudo sed -i 's/server_name _;/&\n\n\terror_page 404 \/error_404.html;\n\tlocation \/error_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Give proper permissions
sudo chown www-data:www-data /var/www/html/error_404.html
sudo chmod 644 /var/www/html/error_404.html

# Restart server
sudo service nginx restart
