#!/usr/bin/env bash
# Configure a new Ubuntu machine running on Nginx
# HTTP response header to request made to this server
# must contain custom header 'X-Served-By'
# value must be the hostname of the server Nginx

sudo apt update # Update package lists

sudo apt install nginx -y # Install nginx

service nginx start # start server

# Configure Nginx server to contain HTTP header X-Served-By
sed -i 's/server_name _;/&\n\n\tlocation {\n\t\tadd_header X-Served-By 54.146.11.39;\n\t\tadd_header X-Served-By 100.25.23.193;\n\n\t\ttry_files \$uri \$uri/ =404;\n\t}/' /etc/nginx/sites-available/default

sudo systemctl reload nginx # reload server
