#!/usr/bin/env bash
# Configure a new Ubuntu machine running on Nginx
# HTTP response header to request made to this server
# must contain custom header 'X-Served-By'
# value must be the hostname of the server Nginx

if [ $(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Nginx is not installed. Installing now..."
	sudo apt-get update
	sudo apt-get install nginx -y
	sudo service nginx start
else
	echo "Nginx is already installed."
fi

# Configure Nginx server to contain HTTP header X-Served-By

sudo sed -i '/^ *server {/a\	add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx reload # reload server
