#!/usr/bin/env bash
# Modify haproxy configuration file
sudo printf 'frontend http-in\n\tbind *:80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 57882-web-01 54.146.11.39\n\tserver 57882-web-02 100.25.23.193' > here
