#!/usr/bin/env bash
# Install HAproxy on load balancer

sudo apt-get update -y # Update
sudo apt-get install build-essential -y # Install required dependecies

sudo apt-get install haproxy -y # Install haproxy

sudo service haproxy start # Start haproxy

# Modify haproxy configuration file
sudo printf 'frontend http-in\n\tbind :*80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 57882-web-01 54.146.11.39 check\n\tserver 57882-web-02 100.25.23.193 check' >> /etc/haproxy/haproxy.cfg

sudo service haproxy reload # reload haproxy
