#!/usr/bin/env bash
# Nginx server to be listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx stop
