#!/usr/bin/env bash
# Bash script that gives you information about the school file.
fil="school"
if [ -e $fil ]
then
	echo "$fil file exists"
	if [ -s $fil ]
	then
		echo "$fil file is not empty"
	else
		echo "$fil file is empty"
	fi
	if [ ! -f $fil ]
	then
		:
	else
		echo "$fil is a regular file"
	fi
else
	echo "$fil file does not exist"
fi
