#!/usr/bin/env bash
# Bash script runs 'whoami' for specifeid user

if [ $# -eq 1 ]
then
	su - "$1" -c "whoami"
	exit 0
else if [ $# -eq 0 ]
	sudo whoami
	exit 0
else
	echo "Usage: $0 <username>"
	exit 1
fi
