#!/usr/bin/env bash
# Configure nginx to run as nginx user and not as root

sudo nginx service stop

sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/server {\n\t/a listen [::]:8080 default_server ipv6only=off;' /etc/nginx/sites-available/default

chmod -R 666 /etc/nginx/nginx.conf
su service nginx start
