#!/usr/bin/env bash
# Configure nginx to run as nginx user and not as root

sudo nginx service stop

sudo sed -i 's/80 /8080 /g' /etc/nginx/sites-available/default

sudo useradd --system --shell /sbin/nologin nginx

sudo sed -i 's/80 /8080 /g' /etc/nginx/nginx.conf

set -e

sudo sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

if [ $? -ne 0 ]; then
	sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
fi

set +e

sudo chmod -R 666 /etc/nginx/nginx.conf

sudo service nginx start
